"""Generate html/apiReference.html from api_data (v3.0.0): every public
function/method with typed positional inputs, name-value options incl.
defaults, and documented outputs. Single source: the arguments blocks
and help text parsed by api_extract."""
import html as H
exec(open('/home/claude/api_data.py').read())
PK = 'shLowLevel'

def esc(s): return H.escape(str(s))

def argrows(args, nv):
    rows = []
    for a in args:
        if bool(a.get('nv')) != nv: continue
        rows.append("<tr><td><code>%s</code></td><td>%s</td><td>%s</td>"
                    "<td>%s</td></tr>" % (esc(a['name']),
                    esc(a.get('size', '') or '-'),
                    esc(a.get('cls', '') or '-'),
                    esc(a.get('default', '') or ('-' if nv else 'required'))))
    return rows

def entry_html(prefix, e):
    nm = (prefix + e['name']) if prefix else e['name']
    s = ['<div class="entry" id="%s">' % esc(nm)]
    s.append('<h3><code>%s(%s)</code></h3>' % (esc(nm), esc(', '.join(e.get('inputs', [])))))
    if e.get('h1'): s.append('<p class="h1line">%s</p>' % esc(e['h1']))
    if e.get('desc'): s.append('<p>%s</p>' % esc(e['desc']))
    pos = argrows(e.get('args', []), False)
    if pos:
        s.append('<b>Inputs</b><table><tr><th>name</th><th>size</th>'
                 '<th>type</th><th>default</th></tr>%s</table>' % ''.join(pos))
    opt = argrows(e.get('args', []), True)
    if opt:
        s.append('<b>Options (name = value)</b><table><tr><th>name</th>'
                 '<th>size</th><th>type</th><th>default</th></tr>%s</table>'
                 % ''.join(opt))
    od = e.get('outdocs') or []
    if od:
        s.append('<b>Outputs</b><table><tr><th>name</th><th>description</th></tr>')
        for o in od:
            s.append('<tr><td><code>%s</code></td><td>%s</td></tr>'
                     % (esc(o[0]), esc(o[1])))
        s.append('</table>')
    elif e.get('outputs'):
        s.append('<b>Outputs</b><p><code>%s</code></p>' % esc(', '.join(e['outputs'])))
    if e.get('example'):
        s.append('<b>Example</b><pre>%s</pre>' % esc(e['example']))
    s.append('</div>')
    return '\n'.join(s)

parts = ["""<!DOCTYPE html><html><head><meta charset="utf-8">
<title>shAnalysis API reference</title>
<style>
body{font-family:Segoe UI,Arial,sans-serif;margin:24px;max-width:960px}
code{background:#f4f4f4;padding:1px 4px}
pre{background:#f4f4f4;padding:8px;overflow-x:auto}
table{border-collapse:collapse;margin:6px 0 14px}
td,th{border:1px solid #ccc;padding:3px 8px;font-size:13px;text-align:left}
.entry{border-top:1px solid #ddd;padding:12px 0}
.h1line{font-weight:bold}
h2{margin-top:34px;border-bottom:2px solid #444}
.toc a{margin-right:10px;font-size:13px}
</style></head><body>
<h1>shAnalysis API reference (v3.0.0)</h1>
<p>Generated from the source arguments blocks and help text - inputs,
name-value options with defaults, and outputs for every public function
and method. Regenerated with every release; the source of truth is the
code itself.</p>"""]

parts.append('<h2>Package functions (shLowLevel.*)</h2><p class="toc">')
for e in sorted(API[PK], key=lambda x: x['name'].lower()):
    parts.append('<a href="#shLowLevel.%s">%s</a>' % (e['name'], e['name']))
parts.append('</p>')
for e in sorted(API[PK], key=lambda x: x['name'].lower()):
    parts.append(entry_html('shLowLevel.', e))

parts.append('<h2>Root functions</h2>')
for e in sorted(API['root'], key=lambda x: x['name'].lower()):
    parts.append(entry_html('', e))

for cl in API['classes']:
    parts.append('<h2>%s methods</h2><p class="toc">' % esc(cl['name']))
    for m in sorted(cl['methods'], key=lambda x: x['name'].lower()):
        parts.append('<a href="#%s.%s">%s</a>' % (cl['name'], m['name'], m['name']))
    parts.append('</p>')
    for m in sorted(cl['methods'], key=lambda x: x['name'].lower()):
        parts.append(entry_html(cl['name'] + '.', m))

parts.append('<hr><p style="font-size:11px;color:#888">Developed by '
             'Matthias Weigelt with the help of Claude (Fable 5), '
             '2026-08-10 (v3.0.0). Generated by tools - do not edit.</p>'
             '</body></html>')
open('/tmp/shx_git/html/apiReference.html', 'w').write('\n'.join(parts))
n = len(API[PK]) + len(API['root']) + sum(len(c['methods']) for c in API['classes'])
print("apiReference.html:", n, "entries")
